### ISSUE TITLE
Integrate ftw.logo for Subsite

### ISSUE THREAD

**Issue by maethu** [4teamwork/ftw.subsite#107]
See https://github.com/4teamwork/ftw.logo

This basically means the custom logo of ftw.subsite is no longer needed and gets replaced by ftw.logo.

- remove subsite logo viewlet
- Use ftw.logo plone.logo viewlet instead
- Migrate logo from ftw.subsite to ftw.logo LOGO scale
- Remove logo field from ftw.subsite

24h

**Comment by busykoala** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate ftw.logo in subsite](https://trello.com/c/0XdFJ1VO/3-integrate-ftwlogo-in-subsite)
