### ISSUE TITLE
add views hardcoded to the onegov logo

### ISSUE THREAD

**Issue by petri** [4teamwork/ftw.subsite#43]
I am trying ftw.subsite with plonetheme.onegov. Works and looks great, except that when adding any content, the edit view always shows the onegov logo???

This happens on Plone 4.3.2 despite setting the subsite logo, the onegov logo and even adding custom logo.jpg to portal_skins/custom.

**Comment by busykoala** [comment]
@maethu, I think this issue could be closed due to our new ftw.logo implementation in ftw.subsite? Therefore the default logo can be set in ftw.logo which now is a dependency.

**Comment by maethu** [comment]
Yep thanks. 

We implemented now the ftw.logo package into the ftw.subsite, which allows you to manage the logo directly.
