### ISSUE TITLE
1.4.x

### ISSUE THREAD

**Issue by maartenkling** [4teamwork/ftw.subsite#64]
Hey,

I (almost) like the 1.4.3 stuff you made, but then using the master branch everything is different and i need to have simplelayout and i dont want that.. any ideas how to continue?

The one thing i need in 1.4.x is to have a class on the body when you are in a subsite so i can assign a themed page to it.

**Comment by jone** [comment]
Hey,

We are currently in progress of rewriting simplelayout ([ftw.simplelayout](https://github.com/4teamwork/ftw.simplelayout)).

So the `master` of `ftw.subsite` will require `ftw.simplelayout` and will be `ftw.subsite = 2.0.0`.
The development of the `1.x` version can be continued on the [1.x](https://github.com/4teamwork/ftw.subsite/tree/1.x) branch.

So I think you'll need to continue using the `1.x` series unless you want to use `ftw.simplelayout`. If you want to continue development there, you can just use the `1.x` branch and send us pull requests against this branch :wink:

**Comment by maartenkling** [comment]
okay
