### ISSUE TITLE
Do not use getattr to get the logo

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.subsite#75]
In https://github.com/4teamwork/ftw.subsite/blob/master/ftw/subsite/viewlets/subsitelogoviewlet.py#L24 the logo is accessed through `subsite_logo = getattr(self.context, 'logo', None)`

This works as long as there is no other attribute `logo`on the context. If the user creates a page or a textblock called "Logo", the ID will be "logo". The viewlet will fail because it will return the textblock instead the logo.

**Comment by maethu** [comment]
The new new logo implementation uses ftw.logo. The logo viewlet in this package has been removed.
