### ISSUE TITLE
Bad markup for languageselector

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.subsite#79]
In the commit https://github.com/4teamwork/ftw.subsite/commit/de5404c398ba12ce542ef3ea77a8fbbaedb333f7 the markup of the languageselector was changed because of miss-used definition list.

Unfortunately the `dropdown.js` which generates the dropdown from CMFPlone: https://github.com/plone/Products.CMFPlone/blob/4.3.9/Products/CMFPlone/skins/plone_ecmascript/dropdown.js needed exactly the previous markup to work properly.

Todo:
- [ ] Revert the commit https://github.com/4teamwork/ftw.subsite/commit/de5404c398ba12ce542ef3ea77a8fbbaedb333f7

@maethu this commit was implemented by you. Is this ok? Or where there other reasons why you changed the markup?

**Comment by maethu** [comment]
❗ I would rather implement a dowpdown.js which can handle both. We may implement the one from bern.ch . It has only minimal changes (like remove dd/dl/dt tags in selectors). 

Info:
Usually the sites only have 2, or 3 Langauges available and there is no need of a dropdown. 


I'm j

**Comment by elioschmutz** [comment]
@raphael-s FYI

**Comment by elioschmutz** [comment]
Ok. So we'll implement the new `dropdown.js` only for the customer itself and not for this (`ftw.subsite`) package.

I will reopen a new Issue in the Customer-Package
