### ISSUE TITLE
Remove "subsite_view"

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/ftw.subsite#90]
This has been announced in the README (https://github.com/4teamwork/ftw.subsite/blame/d537403fbd10d3553d17ab512c8b9ae0a94a1dc8/README.rst#L49):

> The subsite_view will be available in `ftw.subsite` 2.0.x and removed in 2.1.x.

2.1.0 has already been released but the view has not been removed yet.

**Comment by busykoala** [comment]
The subsite_view does not exist anymore. I think it was removed with the plone 5.1 update.
